# Generated by Django 3.0.5 on 2020-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_desc', models.TextField()),
                ('post_author', models.CharField(max_length=100)),
                ('post_pub_date', models.DateTimeField()),
                ('post_slug', models.CharField(max_length=300)),
            ],
        ),
    ]
