# Generated by Django 3.0.5 on 2020-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_thumb',
            field=models.ImageField(default='', upload_to='static/blog/thumbnails'),
            preserve_default=False,
        ),
    ]
