# Generated by Django 3.0.5 on 2020-05-05 07:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200505_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_of_sub',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.date.today),
            preserve_default=False,
        ),
    ]
