# Generated by Django 3.0.5 on 2020-05-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_date_of_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_of_sub',
            new_name='sub_date',
        ),
    ]
