# Generated by Django 3.0.5 on 2020-05-05 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200505_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
